/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Backend.*;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Chunn
 */
public class Client extends javax.swing.JFrame {
    BroadcastSocket client ;
    boolean ketnoi=false;
    public Client() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConectiBT = new javax.swing.JButton();
        AVTServer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpClient = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(108, 217, 220));

        jPanel1.setBackground(new java.awt.Color(108, 217, 220));
        jPanel1.setLayout(null);

        ConectiBT.setBackground(new java.awt.Color(51, 153, 0));
        ConectiBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConectiBT.setForeground(new java.awt.Color(255, 255, 255));
        ConectiBT.setText("Kết Nối");
        ConectiBT.setBorderPainted(false);
        ConectiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectiBTActionPerformed(evt);
            }
        });
        jPanel1.add(ConectiBT);
        ConectiBT.setBounds(260, 503, 350, 30);

        AVTServer.setBackground(new java.awt.Color(108, 217, 220));
        AVTServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/client_SVIcon.png"))); // NOI18N
        AVTServer.setBorderPainted(false);
        jPanel1.add(AVTServer);
        AVTServer.setBounds(0, 10, 120, 90);

        jScrollPane1.setViewportView(txpClient);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 40, 640, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectiBTActionPerformed
        // TODO add your handling code here:
        ketnoi=!ketnoi;
        if(ketnoi){
        ConectiBT.setText("Hủy Kết Nối");
            try {
                client = new BroadcastSocket(txpClient);
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                client.remove();
                txpClient.setText(txpClient.getText()+ "Disconnect..."+"\n");
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            ConectiBT.setText("Kết Nối");
        }
    }//GEN-LAST:event_ConectiBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AVTServer;
    private javax.swing.JButton ConectiBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txpClient;
    // End of variables declaration//GEN-END:variables
}
